/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;


import java.awt.*;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author DAW6K
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setWindowIcon();
        PanelTitulo.setVisible(true);
        PanelEventos.setVisible(false);
        InicioProximosEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        EventosT = new javax.swing.JToggleButton();
        InicioT = new javax.swing.JToggleButton();
        destacados = new javax.swing.JPanel();
        PanelEventos = new javax.swing.JPanel();
        TituloEventos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TickAura");

        PanelGeneral.setMinimumSize(new java.awt.Dimension(100, 10000));

        PanelTitulo.setMinimumSize(new java.awt.Dimension(600, 800));

        Titulo.setText("INICIO MAMAÑEMA");

        EventosT.setLabel("Eventos");
        EventosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosTActionPerformed(evt);
            }
        });

        InicioT.setLabel("Inicio");
        InicioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout destacadosLayout = new javax.swing.GroupLayout(destacados);
        destacados.setLayout(destacadosLayout);
        destacadosLayout.setHorizontalGroup(
            destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        destacadosLayout.setVerticalGroup(
            destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventosT)
                .addGap(42, 42, 42))
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(Titulo))
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(destacados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventosT)
                    .addComponent(InicioT))
                .addGap(34, 34, 34)
                .addComponent(destacados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TituloEventos.setText("EVENTOS MAMAÑEMA");

        javax.swing.GroupLayout PanelEventosLayout = new javax.swing.GroupLayout(PanelEventos);
        PanelEventos.setLayout(PanelEventosLayout);
        PanelEventosLayout.setHorizontalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEventosLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(TituloEventos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEventosLayout.setVerticalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEventosLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(TituloEventos)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9406, Short.MAX_VALUE)
                .addComponent(PanelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosTActionPerformed
        // TODO add your handling code here:
        PanelTitulo.hide();
        PanelEventos.show();
    }//GEN-LAST:event_EventosTActionPerformed

    private void InicioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioTActionPerformed
        // TODO add your handling code here:
        PanelTitulo.show();
        PanelEventos.hide();
        InicioProximosEventos();
    }//GEN-LAST:event_InicioTActionPerformed

    public void InicioProximosEventos() {
        
        destacados.removeAll(); // Limpiar el panel antes de agregar nuevos elementos
        destacados.setLayout(new java.awt.GridLayout(2, 4, 10, 10)); // 2 filas, 4 columnas, 10px de espacio

        for (int i = 0; i < 8; i++) {
            JPanel eventoPanel = new JPanel();
            eventoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
            eventoPanel.setPreferredSize(new java.awt.Dimension(150, 100));
        
            JLabel eventoLabel = new JLabel("Evento " + (i + 1));
            eventoPanel.add(eventoLabel);
            
            destacados.add(eventoPanel);
        }
    
        destacados.revalidate();
        destacados.repaint();
    }
    
    private void setWindowIcon() {
        try {
            Image icon = ImageIO.read(new File("./icono.png")); // Cargar desde archivo local
            setIconImage(icon);
        } catch (IOException e) {
            System.err.println("No se pudo cargar el icono: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EventosT;
    private javax.swing.JToggleButton InicioT;
    private javax.swing.JPanel PanelEventos;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloEventos;
    private javax.swing.JPanel destacados;
    // End of variables declaration//GEN-END:variables
}
