/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;


import java.awt.*;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author DAW6K
 */
public class Interface extends javax.swing.JFrame {

    private int enPantalla;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setWindowIcon();
        PanelTitulo.setVisible(true);
        PanelEventos.setVisible(false);
        InicioProximosEventos();
        enPantalla = PanelTitulo.getY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        EventosT = new javax.swing.JToggleButton();
        InicioT = new javax.swing.JToggleButton();
        destacados = new javax.swing.JPanel();
        PanelEventos = new javax.swing.JPanel();
        TituloEventos = new javax.swing.JLabel();
        EventosE = new javax.swing.JToggleButton();
        InicioE = new javax.swing.JToggleButton();
        tipoEvento = new javax.swing.JComboBox<>();
        precioEvento = new javax.swing.JSlider();
        valorPrecioEvento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TickAura");

        PanelGeneral.setMinimumSize(new java.awt.Dimension(100, 1500));
        PanelGeneral.setPreferredSize(new java.awt.Dimension(801, 1500));

        PanelTitulo.setMinimumSize(new java.awt.Dimension(600, 800));

        Titulo.setText("INICIO MAMAĂ‘EMA");

        EventosT.setLabel("Eventos");
        EventosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosTActionPerformed(evt);
            }
        });

        InicioT.setLabel("Inicio");
        InicioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout destacadosLayout = new javax.swing.GroupLayout(destacados);
        destacados.setLayout(destacadosLayout);
        destacadosLayout.setHorizontalGroup(
            destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        destacadosLayout.setVerticalGroup(
            destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventosT)
                .addGap(42, 42, 42))
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(Titulo))
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(destacados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventosT)
                    .addComponent(InicioT))
                .addGap(34, 34, 34)
                .addComponent(destacados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TituloEventos.setText("EVENTOS MAMAĂ‘EMA");

        EventosE.setLabel("Eventos");
        EventosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosEActionPerformed(evt);
            }
        });

        InicioE.setLabel("Inicio");
        InicioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioEActionPerformed(evt);
            }
        });

        tipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Concierto", "Teatro", "Evento", "Festival" }));
        tipoEvento.setPreferredSize(new java.awt.Dimension(80, 20));

        precioEvento.setMaximum(500);
        precioEvento.setPaintLabels(true);
        precioEvento.setValue(500);
        precioEvento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                precioEventoStateChanged(evt);
            }
        });

        valorPrecioEvento.setText("TODOS");

        javax.swing.GroupLayout PanelEventosLayout = new javax.swing.GroupLayout(PanelEventos);
        PanelEventos.setLayout(PanelEventosLayout);
        PanelEventosLayout.setHorizontalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloEventos)
                .addGap(329, 329, 329))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEventosLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(tipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorPrecioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventosE)
                .addGap(43, 43, 43))
        );
        PanelEventosLayout.setVerticalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEventosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(TituloEventos)
                .addGap(18, 18, 18)
                .addGroup(PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventosE)
                    .addComponent(InicioE)
                    .addComponent(tipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorPrecioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8904, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   /**
 * Método que se ejecuta cuando se pulsa el botón "Eventos" en el panel de inicio.
 * Oculta el panel de título y muestra el panel de eventos.
 * 
 * @param evt Evento de acción generado por hacer clic en el botón "Eventos".
 */
    private void EventosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosTActionPerformed
        // TODO add your handling code here:
        PanelTitulo.hide();
        PanelEventos.setLocation(PanelEventos.getX(), enPantalla);
        PanelEventos.show();
    }//GEN-LAST:event_EventosTActionPerformed
/**
 * Método que se ejecuta al pulsar el botón "Inicio" desde el panel de inicio.
 * Oculta el panel de eventos y muestra el panel de título.
 * 
 * @param evt Evento de acción generado por hacer clic en el botón "Inicio".
 */
    private void InicioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioTActionPerformed
        // TODO add your handling code here:
        PanelEventos.hide();
        PanelTitulo.show();
        InicioProximosEventos();
    }//GEN-LAST:event_InicioTActionPerformed
/**
 * Método que se ejecuta al pulsar el botón "Inicio" desde el panel de eventos.
 * Oculta el panel de eventos y muestra el panel de título.
 * 
 * @param evt Evento de acción generado por hacer clic en el botón "Inicio".
 */
    private void InicioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioEActionPerformed
        // TODO add your handling code here:
        PanelEventos.hide();
        PanelTitulo.show();
        InicioProximosEventos();
    }//GEN-LAST:event_InicioEActionPerformed
/**
 * Método que se ejecuta cuando se pulsa el botón "Eventos" desde el panel de eventos.
 * Oculta el panel de título y vuelve a mostrar el panel de eventos.
 * 
 * @param evt Evento de acción generado por hacer clic en el botón "Eventos".
 */
    private void EventosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosEActionPerformed
        // TODO add your handling code here:
        PanelTitulo.hide();
        PanelEventos.setLocation(PanelEventos.getX(), enPantalla);
        PanelEventos.show();
    }//GEN-LAST:event_EventosEActionPerformed
/**
 * Método que se ejecuta cuando se cambia el valor del slider de precio.
 * Actualiza el texto de la etiqueta `valorPrecioEvento` para mostrar el precio seleccionado o "TODOS".
 * 
 * @param evt Evento de cambio generado por mover el slider de precio.
 */
    private void precioEventoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_precioEventoStateChanged
        // TODO add your handling code here:
        if (precioEvento.getValue() == 500) {
            valorPrecioEvento.setText("TODOS");
        } else {
            valorPrecioEvento.setText("< "+precioEvento.getValue()+"â‚¬");
        }
    }//GEN-LAST:event_precioEventoStateChanged
/**
 * Método que se encarga de inicializar y mostrar los próximos eventos en el panel "destacados".
 * Crea 8 paneles con etiquetas que simulan eventos.
 */
    public void InicioProximosEventos() {
        
        destacados.removeAll(); // Limpiar el panel antes de agregar nuevos elementos
        destacados.setLayout(new java.awt.GridLayout(2, 4, 10, 10)); // 2 filas, 4 columnas, 10px de espacio

        for (int i = 0; i < 8; i++) {
            JPanel eventoPanel = new JPanel();
            eventoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
            eventoPanel.setPreferredSize(new java.awt.Dimension(150, 100));
        
            JLabel eventoLabel = new JLabel("Evento " + (i + 1));
            eventoPanel.add(eventoLabel);
            
            destacados.add(eventoPanel);
        }
    
        destacados.revalidate();
        destacados.repaint();
    }
    /**
 * Establece el icono de la ventana a partir de un archivo local llamado "icono.png".
 * Si no se encuentra el archivo o ocurre un error, se imprime un mensaje de error en consola.
 */
    private void setWindowIcon() {
        try {
            Image icon = ImageIO.read(new File("./icono.png")); // Cargar desde archivo local
            setIconImage(icon);
        } catch (IOException e) {
            System.err.println("No se pudo cargar el icono: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EventosE;
    private javax.swing.JToggleButton EventosT;
    private javax.swing.JToggleButton InicioE;
    private javax.swing.JToggleButton InicioT;
    private javax.swing.JPanel PanelEventos;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloEventos;
    private javax.swing.JPanel destacados;
    private javax.swing.JSlider precioEvento;
    private javax.swing.JComboBox<String> tipoEvento;
    private javax.swing.JLabel valorPrecioEvento;
    // End of variables declaration//GEN-END:variables
}
