/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;


import java.awt.*;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

// IMPORT DEL SQL
import java.sql.*;

/**
 * @version 1.1.0
 * @author DAW6K
 * 
 */

public class Interface extends javax.swing.JFrame {

    private int enPantalla;
    
    /**
     * Creates new form Interface
     * 
     */
    public Interface() {
        initComponents();
        setWindowIcon();
        PanelTitulo.setVisible(true);
        PanelEventos.setVisible(false);
        enPantalla = PanelTitulo.getY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        EventosT = new javax.swing.JToggleButton();
        InicioT = new javax.swing.JToggleButton();
        destacados = new javax.swing.JPanel();
        NombreEvento = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        FechaEvento = new javax.swing.JTextField();
        FechaLabel = new javax.swing.JLabel();
        UbicacionEvento = new javax.swing.JLabel();
        UbicacionLabel = new javax.swing.JTextField();
        PrecioEvento = new javax.swing.JLabel();
        PrecioLabel = new javax.swing.JTextField();
        DestacadoLabel = new javax.swing.JLabel();
        CheckBoxEvento = new javax.swing.JCheckBox();
        ComboEvento = new javax.swing.JComboBox<>();
        ComboLabel = new javax.swing.JLabel();
        AnadirEvento = new javax.swing.JButton();
        PanelEventos = new javax.swing.JPanel();
        TituloEventos = new javax.swing.JLabel();
        EventosE = new javax.swing.JToggleButton();
        InicioE = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TickAura");

        PanelGeneral.setMinimumSize(new java.awt.Dimension(100, 1500));
        PanelGeneral.setPreferredSize(new java.awt.Dimension(801, 1500));

        PanelTitulo.setMinimumSize(new java.awt.Dimension(600, 800));

        Titulo.setText("INICIO MAMAÑEMA");

        EventosT.setLabel("Eventos");
        EventosT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosTActionPerformed(evt);
            }
        });

        InicioT.setLabel("Inicio");
        InicioT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioTActionPerformed(evt);
            }
        });

        NombreLabel.setText("Nombre:");

        FechaLabel.setText("Fecha:");

        UbicacionEvento.setText("Ubicación:");

        UbicacionLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbicacionLabelActionPerformed(evt);
            }
        });

        PrecioEvento.setText("Precio:");

        PrecioLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioLabelActionPerformed(evt);
            }
        });

        DestacadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DestacadoLabel.setText("DEST");

        CheckBoxEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckBoxEvento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ComboEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concierto", "Evento", "Festival", "Teatro" }));

        ComboLabel.setText("Tipo:");

        AnadirEvento.setText("Añadir Evento");
        AnadirEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout destacadosLayout = new javax.swing.GroupLayout(destacados);
        destacados.setLayout(destacadosLayout);
        destacadosLayout.setHorizontalGroup(
            destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destacadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreEvento)
                    .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FechaEvento)
                    .addComponent(FechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UbicacionLabel)
                    .addComponent(UbicacionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PrecioLabel)
                    .addComponent(PrecioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DestacadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(CheckBoxEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboEvento, 0, 102, Short.MAX_VALUE)
                    .addComponent(ComboLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, destacadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnadirEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        destacadosLayout.setVerticalGroup(
            destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destacadosLayout.createSequentialGroup()
                .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(destacadosLayout.createSequentialGroup()
                        .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DestacadoLabel)
                            .addComponent(ComboLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PrecioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CheckBoxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ComboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(destacadosLayout.createSequentialGroup()
                            .addComponent(UbicacionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(UbicacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(destacadosLayout.createSequentialGroup()
                            .addComponent(FechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(destacadosLayout.createSequentialGroup()
                            .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(NombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(AnadirEvento)
                .addGap(116, 116, 116))
        );

        NombreEvento.getAccessibleContext().setAccessibleName("");
        FechaLabel.getAccessibleContext().setAccessibleName("Fecha:");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventosT)
                .addGap(42, 42, 42))
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(Titulo))
                    .addGroup(PanelTituloLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(destacados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventosT)
                    .addComponent(InicioT))
                .addGap(34, 34, 34)
                .addComponent(destacados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TituloEventos.setText("EVENTOS MAMAÑEMA");

        EventosE.setLabel("Eventos");
        EventosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventosEActionPerformed(evt);
            }
        });

        InicioE.setLabel("Inicio");
        InicioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEventosLayout = new javax.swing.GroupLayout(PanelEventos);
        PanelEventos.setLayout(PanelEventosLayout);
        PanelEventosLayout.setHorizontalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloEventos)
                .addGap(329, 329, 329))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventosE)
                .addGap(43, 43, 43))
        );
        PanelEventosLayout.setVerticalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEventosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(TituloEventos)
                .addGap(18, 18, 18)
                .addGroup(PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventosE)
                    .addComponent(InicioE))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(PanelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(586, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8904, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void EventosTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosTActionPerformed
        // TODO add your handling code here:
        PanelTitulo.hide();
        PanelEventos.setLocation(PanelEventos.getX(), enPantalla);
        PanelEventos.show();
    }//GEN-LAST:event_EventosTActionPerformed

    private void InicioTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioTActionPerformed
        // TODO add your handling code here:
        PanelEventos.hide();
        PanelTitulo.show();
    }//GEN-LAST:event_InicioTActionPerformed

    private void InicioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioEActionPerformed
        // TODO add your handling code here:
        PanelEventos.hide();
        PanelTitulo.show();
    }//GEN-LAST:event_InicioEActionPerformed

    private void EventosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventosEActionPerformed
        // TODO add your handling code here:
        PanelTitulo.hide();
        PanelEventos.setLocation(PanelEventos.getX(), enPantalla);
        PanelEventos.show();
    }//GEN-LAST:event_EventosEActionPerformed

    private void UbicacionLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacionLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbicacionLabelActionPerformed

    private void PrecioLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioLabelActionPerformed

    private void AnadirEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirEventoActionPerformed
        // TODO add your handling code here:
        String nombre = NombreEvento.getText();
        String fechaTexto = FechaEvento.getText(); // formato: yyyy-MM-dd
        String ubicacion = UbicacionEvento.getText();
        String precioTexto = PrecioEvento.getText();
        boolean destacado = CheckBoxEvento.isSelected();
        String tipoEvento = (String) ComboEvento.getSelectedItem();
        
        System.out.println("Valor de fechaTexto: [" + fechaTexto + "]");

        // 2. Validaciones básicas (opcional)
        if (nombre.isEmpty() || fechaTexto.isEmpty() || precioTexto.isEmpty() || tipoEvento == null) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena todos los campos obligatorios.");
            return;
        }

        try {
            // 3. Convertir tipos
            java.sql.Date fecha = java.sql.Date.valueOf(fechaTexto); // yyyy-MM-dd
            double precio = Double.parseDouble(precioTexto);
            int destacadoInt = destacado ? 1 : 0;

            // 4. Conectar a Oracle
            Connection conn = OracleConnection.conectar();
            String sql = "INSERT INTO Eventos (nombre, fecha, ubicacion, precio, destacado, tipo_evento) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nombre);
            ps.setDate(2, fecha);
            ps.setString(3, ubicacion);
            ps.setDouble(4, precio);
            ps.setInt(5, destacadoInt);
            ps.setString(6, tipoEvento);

            int filasInsertadas = ps.executeUpdate();
            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(this, "Evento añadido correctamente.");
                // Limpia campos si quieres
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo añadir el evento.");
            }

            // 5. Cerrar conexión
            ps.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en base de datos: " + e.getMessage());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa yyyy-MM-dd.");
        }                
    }//GEN-LAST:event_AnadirEventoActionPerformed

    
    private void setWindowIcon() {
        try {
            Image icon = ImageIO.read(new File("./icono.png")); // Cargar desde archivo local
            setIconImage(icon);
        } catch (IOException e) {
            System.err.println("No se pudo cargar el icono: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
        
        Connection conn = OracleConnection.conectar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirEvento;
    private javax.swing.JCheckBox CheckBoxEvento;
    private javax.swing.JComboBox<String> ComboEvento;
    private javax.swing.JLabel ComboLabel;
    private javax.swing.JLabel DestacadoLabel;
    private javax.swing.JToggleButton EventosE;
    private javax.swing.JToggleButton EventosT;
    private javax.swing.JTextField FechaEvento;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JToggleButton InicioE;
    private javax.swing.JToggleButton InicioT;
    private javax.swing.JTextField NombreEvento;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JPanel PanelEventos;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel PrecioEvento;
    private javax.swing.JTextField PrecioLabel;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloEventos;
    private javax.swing.JLabel UbicacionEvento;
    private javax.swing.JTextField UbicacionLabel;
    private javax.swing.JPanel destacados;
    // End of variables declaration//GEN-END:variables
}
